[package]
name = "socials-app"
version.workspace = true
edition.workspace = true

[dependencies]
tauri = { version = "2", features = [] }
tokio.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lib]
name = "socials_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]
